//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.ItemPersonnel = new HashSet<ItemPersonnel>();
            this.ResearchItem = new HashSet<ResearchItem>();
            this.ResearchPaper = new HashSet<ResearchPaper>();
        }
    
        public int Id { get; set; }
        public string Account { get; set; }
        public string Pwd { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string Tel { get; set; }
        public string Title { get; set; }
        public string major { get; set; }
        public string College { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
    
        public virtual ICollection<ItemPersonnel> ItemPersonnel { get; set; }
        public virtual ICollection<ResearchItem> ResearchItem { get; set; }
        public virtual ICollection<ResearchPaper> ResearchPaper { get; set; }
    }
}
