//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgriculturalResearchEntities : DbContext
    {
        public AgriculturalResearchEntities()
            : base("name=AgriculturalResearchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<ExpRecord> ExpRecord { get; set; }
        public DbSet<ItemPersonnel> ItemPersonnel { get; set; }
        public DbSet<Person> Person { get; set; }
        public DbSet<ResearchItem> ResearchItem { get; set; }
        public DbSet<ResearchPaper> ResearchPaper { get; set; }
        public DbSet<Achievements> Achievements { get; set; }
    }
}
